import { TaskPriority, TaskStatus, TaskType } from "./enums";
import { IComment, IProject, ITask } from "./types";

export const mockProjects: IProject[] = [
  {
    name: "My Movie List - FE",
    code: "MML-FE",
    manager: "sumitks866",
  },
  {
    name: "Typeracer",
    code: "TRC",
    manager: "suyashmadhesia",
  },
];

export const mockTasks: ITask[] = [
  {
    projectCode: "TRC",
    taskCode: "TRC-001",
    status: TaskStatus.DEVELOPMENT_COMPLETE,
    type: TaskType.FIX,
    title: "Implement Login Functionality",
    description:
      'The task involves developing a user-friendly login system for our frontend application, necessitating the creation of a login interface where users can input their username/email and password to access the platform. The primary objective is to ensure secure authentication, handling valid and invalid credentials appropriately with clear error messaging. To achieve this, implement a responsive login page with necessary input fields and a "Login" button, enabling users to log in securely. Utilize encryption methods for password security and HTTPS for data encryption during transmission. Additionally, include a "Remember Me" option for user convenience across sessions. Testing across various environments is crucial to validate functionality, encompassing valid input scenarios, error handling, and overall usability checks. This task should be completed in line with the specified deadline, following collaboration with backend developers for seamless integration and adhering to security best practices throughout the development process.',
    reporterId: "user123",
    stargazers: ["user456", "user789"],
    createdAt: "2023-12-01T09:00:00Z",
    updatedAt: "2023-12-05T15:30:00Z",
    relatedIssuesCode: ["ISSUE-001", "ISSUE-002"],
    commentsId: ["comment123", "comment456"],
    storyPoints: "5",
    priority: TaskPriority.CRITICAL,
    acceptanceCriteria:
      'The system should authenticate user credentials, providing clear error messages for any login failures or incorrect inputs. To ensure security, passwords must be encrypted before storage and transmission, employing HTTPS for secure data transfer. Additionally, incorporating a "Remember Me" feature enables users to stay logged in across sessions, enhancing user convenience. The login interface should be designed to work seamlessly on various devices and screen sizes, ensuring accessibility for users with disabilities. Rigorous testing across different environments is necessary to validate functionality, checking for valid and invalid inputs and overall usability to guarantee a reliable login experience for users.',
  },
  {
    projectCode: "MAP",
    taskCode: "MAP-FEAT-1234",
    status: TaskStatus.MR_CREATED,
    type: TaskType.IMPROVEMENT,
    title: "Implement multi-language support",
    description:
      "Make the application accessible to users in different regions by adding language translation functionality.",
    assigneeId: "emma.lopez",
    reporterId: "john.doe",
    priority: TaskPriority.MAJOR,
    labels: ["internationalization", "accessibility", "user experience"],
    stargazers: ["alice.smith", "michael.chen"],
    createdAt: "2023-12-15",
    updatedAt: "2023-12-16",
    relatedIssuesCode: [],
    commentsId: ["1", "3", "5"],
    storyPoints: "3",
  },
  {
    projectCode: "TRC",
    taskCode: "TRC-002",
    status: TaskStatus.MERGED,
    priority: TaskPriority.MINOR,
    type: TaskType.TASK,
    title: "Fix Image Loading Issue",
    description: "Resolve issue causing images not to load properly.",
    reporterId: "user789",
    stargazers: [],
    createdAt: "2023-12-10T10:30:00Z",
    updatedAt: "2023-12-12T14:45:00Z",
    relatedIssuesCode: [],
    commentsId: [],
  },
  {
    projectCode: "ECP",
    taskCode: "ECP-BUG-987",
    status: TaskStatus.VERIFIED,
    type: TaskType.FEATURE,
    title: "Product image not loading on mobile",
    description:
      "Certain product images are not displaying correctly on mobile devices.",
    reporterId: "jane.wilson",
    priority: TaskPriority.MEDIUM,
    labels: ["mobile", "ecommerce", "visual bug"],
    createdAt: "2023-12-14",
    updatedAt: "2023-12-16",
    relatedIssuesCode: ["ECP-FEAT-456"],
    commentsId: [],
    stargazers: [],
    storyPoints: "1",
  },
  {
    projectCode: "TRC",
    taskCode: "TRC-003",
    status: TaskStatus.DONE,
    type: TaskType.EPIC,
    title: "Update User Profile Page",
    description: "Enhance user profile page UI and add new features.",
    reporterId: "user234",
    stargazers: ["user567"],
    createdAt: "2023-11-25T14:00:00Z",
    updatedAt: "2023-11-30T16:20:00Z",
    relatedIssuesCode: ["ISSUE-003"],
    commentsId: ["comment789"],
    priority: TaskPriority.CRITICAL,
    assigneeId: "sumitks866",
  },
  {
    projectCode: "CMS",
    taskCode: "CMS-QA-012",
    status: TaskStatus.IN_PROGRESS,
    type: TaskType.REQUEST,
    title: "Review new content management system features",
    description:
      "Work with the development team to test and provide feedback on the functionality and usability of new CMS features.",
    assigneeId: "emily.garcia",
    qaContactId: "christopher.williams",
    reporterId: "david.lee",
    priority: TaskPriority.BLOCKER,
    labels: ["testing", "content management", "internal"],
    createdAt: "2023-12-12",
    updatedAt: "2023-12-16",
    relatedIssuesCode: [],
    commentsId: [],
    stargazers: [],
    storyPoints: "8",
  },
  {
    projectCode: "PROJ-001",
    taskCode: "TASK-004",
    status: TaskStatus.ACCEPTED,
    type: TaskType.DOC,
    title:
      "Implementing robust encryption protocols to secure user data transfer across distributed systems in a microservices architecture. ",
    description: "There is an alignment problem in the header section.",
    storyPoints: "3",
    reporterId: "user123",
    stargazers: ["user456", "user789"],
    createdAt: "2023-10-15T08:00:00Z",
    updatedAt: "2023-10-17T14:30:00Z",
    relatedIssuesCode: [],
    commentsId: [],
  },
  {
    projectCode: "PROJ-002",
    taskCode: "TASK-005",
    status: TaskStatus.DEFERRED,
    type: TaskType.REPORT,
    title: "Implement search functionality",
    description: "Add search feature with filters.",
    assigneeId: "user789",
    reporterId: "user456",
    stargazers: [],
    createdAt: "2023-09-20T11:45:00Z",
    updatedAt: "2023-09-22T16:20:00Z",
    relatedIssuesCode: [],
    commentsId: ["comment123"],
  },
  {
    projectCode: "TRC",
    taskCode: "TRC-008",
    status: TaskStatus.REJECTED,
    type: TaskType.STORY,
    title: "Update user authentication",
    description: "Revamp user authentication system for better security.",
    reporterId: "user789",
    stargazers: ["user123"],
    createdAt: "2023-11-05T09:30:00Z",
    updatedAt: "2023-11-10T15:45:00Z",
    relatedIssuesCode: ["ISSUE-001"],
    commentsId: ["comment456", "comment789"],
    priority: TaskPriority.MEDIUM,
  },
];

export const mockComments: IComment[] = [
  {
    id: "1",
    taskId: "task_1",
    content: `This is an insightful comment regarding the task progress. 
    It provides detailed information about the challenges faced 
    and possible solutions.`,
    userId: "user_1",
    createdAt: "2023-12-01T10:00:00Z",
    editedAt: "2023-12-01T11:30:00Z",
  },
  {
    id: "2",
    taskId: "task_2",
    content: `I've reviewed the recent changes and everything seems to be 
    working fine. Great work by the team!`,
    userId: "user_2",
    createdAt: "2023-12-02T09:15:00Z",
  },
  {
    id: "3",
    taskId: "task_3",
    content: `We encountered a few issues during the implementation. 
    Looking for suggestions to address these problems.`,
    userId: "user_3",
    createdAt: "2023-12-03T14:20:00Z",
  },
  {
    id: "4",
    taskId: "task_4",
    content: `I'm sharing some additional details that might be relevant 
    to this task. Please review and provide your insights.`,
    userId: "user_1",
    createdAt: "2023-12-04T12:45:00Z",
  },
  {
    id: "5",
    taskId: "task_5",
    content: `The latest update seems promising. Looking forward to further 
    improvements and enhancements.`,
    userId: "user_2",
    createdAt: "2023-12-05T08:30:00Z",
    editedAt: "2023-12-06T09:20:00Z",
  },
  {
    id: "6",
    taskId: "task_6",
    content: `The proposed enhancement aligns well with the user feedback 
    we've received in recent surveys. Let's discuss this in the upcoming meeting.`,
    userId: "user_1",
    createdAt: "2023-12-06T10:00:00Z",
  },
  {
    id: "7",
    taskId: "task_7",
    content: `We've encountered a similar issue in the past. I suggest 
    cross-referencing it with the previous resolution to expedite the fix.`,
    userId: "user_2",
    createdAt: "2023-12-07T11:15:00Z",
  },
  {
    id: "8",
    taskId: "task_8",
    content: `The user interface for this feature needs refinement based 
    on the latest usability test results. Let's iterate on the design.`,
    userId: "user_3",
    createdAt: "2023-12-08T12:30:00Z",
  },
  {
    id: "9",
    taskId: "task_9",
    content: `Regarding the reported bug, it seems to be specific to certain 
    browser versions. We'll need to conduct additional testing for compatibility.`,
    userId: "user_4",
    createdAt: "2023-12-09T13:45:00Z",
    editedAt: "2023-12-10T14:30:00Z",
  },
  {
    id: "10",
    taskId: "task_10",
    content: `The user story is well-documented and provides clear acceptance 
    criteria. Let's proceed with development based on this outline.`,
    userId: "user_5",
    createdAt: "2023-12-10T15:00:00Z",
  },
];
